FROM python:3.11-slim
WORKDIR /app
RUN pip install --no-cache-dir \
    streamlit==1.55.0 \
    sqlalchemy==2.0.48 \
    psycopg2-binary==2.9.11 \
    python-dotenv==1.2.2 \
    plotly==6.1.2 \
    pandas==2.3.3
COPY src/dashboard ./src/dashboard/
EXPOSE 8501
CMD ["streamlit", "run", "src/dashboard/app.py", "--server.port=8501", "--server.address=0.0.0.0"]